# Common sections
defaults: &defaults
  docker:
    - image: dmp1ce/archlinux-yay
  steps:
    - run:
        name: Update packages
        command: sudo pacman -Syu --noconfirm
    - run:
        name: Build package
        command: yay -S --noconfirm ${CIRCLE_JOB}

# Main
version: 2
jobs:
  bisq:
    <<: *defaults
  bisq-bin:
    <<: *defaults
  bisq-git:
    <<: *defaults
  lnd:
    <<: *defaults
  zap-desktop-bin:
    <<: *defaults
  pybitmessage-git:
    <<: *defaults
  lando:
    <<: *defaults
  lando-git:
    <<: *defaults
  diffutils-git:
    <<: *defaults
  check_smartmon-git:
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
      - bisq
      - bisq-bin
      - bisq-git
      - lnd
      - zap-desktop-bin
      - pybitmessage-git
      - lando
      - lando-git
      - diffutils-git
      - check_smartmon-git
