# Common sections
defaults: &defaults
  docker:
    - image: dmp1ce/archlinux-yay
  steps:
    - run:
        name: Update packages
        command: sudo pacman -Syu --noconfirm
    - run:
        name: Build package
        command: yay --useask -S --noconfirm ${CIRCLE_JOB}

# Main
version: 2
jobs:
  whirlpool-gui-appimage:
    <<: *defaults
  bisq:
    <<: *defaults
  bisq-bin:
    <<: *defaults
  bisq-git:
    <<: *defaults
  lnd:
    <<: *defaults
  zap-desktop-appimage:
    <<: *defaults
  pybitmessage-git:
    <<: *defaults
  lando:
    <<: *defaults
  lando-git:
    <<: *defaults
  check_smartmon-git:
    <<: *defaults
  python2-simple-crypt:
    <<: *defaults
  mo-git:
    <<: *defaults
  list-all-systemd-timers-git:
    <<: *defaults
  decompose-git:
    <<: *defaults
  coinbin-git:
    <<: *defaults
  check_zfs-git:
    <<: *defaults
  check_pacman-git:
    <<: *defaults
  bitaddress-git:
    <<: *defaults
  bip39tool-git:
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
      - whirlpool-gui-appimage
      - bip39tool-git
      - bitaddress-git
      - check_pacman-git
      - check_zfs-git
      - bisq
      - bisq-bin
      - bisq-git
      - lnd
      - zap-desktop-appimage
      - pybitmessage-git
      - lando
      - lando-git
      - diffutils-git
      - check_smartmon-git
      - python2-simple-crypt
      - mo-git
      - list-all-systemd-timers-git
      - diffutils-patched-exclude-directory-git
      - decompose-git
      - coinbin-git
