# Common sections
defaults: &defaults
  docker:
    - image: dmp1ce/archlinux-yay

updatepackage: &update
  name: Update packages
  command: sudo pacman -Syu --noconfirm

gitupdate: &buildpkgbuild
  name: Build package
  command: yay -S --noconfirm ${CIRCLE_JOB}

# Main
version: 2
jobs:
  bisq-bin:
    <<: *defaults
    steps:
      - run:
          <<: *update
      - run:
          <<: *buildpkgbuild

workflows:
  version: 2
  build:
    jobs:
      - bisq-bin
